language: java

jdk:
  - oraclejdk8

before_install:
  git clone https://github.com/netty/netty.git
  cd netty
  mvn install -DskipTests --quiet
  cd ..

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master  

script: "mvn verify -X"